apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-app
  labels:
    app: my-springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-springboot-app
  template:
    metadata:
      labels:
        app: my-springboot-app
    spec:
      containers:
        - name: my-springboot-app-container
          image: pranav1706/my-spring-app:latest  # Use your Docker image here
          ports:
            - containerPort: 8080  # The port your Spring Boot app is running on
