apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-app
  labels:
    app: my-springboot-app
spec:
  replicas: 
  selector:
    matchLabels:
      app: my-springboot-app
  template:
    metadata:
      labels:
        app: my-springboot-app
    spec:
      containers:
        - name: my-springboot-app-container
          image: pranav1706/my-spring-app:latest  # Use your Docker image here
          ports:
            - containerPort: 8080  # The port your Spring Boot app is running on
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # You can adjust this if you're using profiles
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"