# Group Members:
# Pranav Manish Reddi Madduri - G01504276
# Lavanya Jillela - G01449670
# Sneha Rathi - G01449688
# Chennu Naga Venkata Sai - G01514409
apiVersion: v1
kind: Service
metadata:
  name: my-springboot-app-service
spec:
  selector:
    app: my-springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # This should match the containerPort in the deployment
  type: LoadBalancer  # You can change this to ClusterIP or NodePort depending on your setup